### ISSUE TITLE
Ambiguous Redirect error when attempting to run sample code.

### ISSUE THREAD

**Issue by jroakes** [qadium-memex/CommonCrawlJob#3]
I noticed that aws (__main__.py) would throw an error on:
`from . import S3Remote`
so I changed to 
`from aws import S3Remote` 
and that resolved the error.

I have configured the mrjob.conf file per the template and included data/latest.txt in the dame directory as GoogleAnalytics.py

This is the folder setup: http://screencast.com/t/v86TY8RW

I also followed the rest of the Example instructions, but when I run:

`python GoogleAnalytics.py -r emr --conf-path="mrjob.conf" --output-dir='s3://my-s3-bucket' < $(python -m aws)`

I receive the following error:
-bash: $(python -m aws): ambiguous redirect`

Any guidance would be appreciated.

**Comment by jjangsangy** [comment]
Give this a try

```bash
python -m aws > myfile.txt
ython GoogleAnalytics.py -r emr --conf-path="mrjob.conf" --output-dir='s3://my-s3-bucket' myfile.txt
```

**Comment by jroakes** [comment]
Thanks.  It looks like the mrjob.conf example is using parameters from an older version of mrjob.  Working on converting but the config documentation for mrjob is pretty sparse.

**Comment by jroakes** [comment]
This is the config file that worked for me with the latest version of mrjob:
```
# A config file template to build off for running in production
#
# If you don't have the yaml module installed, you'll have to use JSON instead,
# which would look something like this:

runners:
  emr:
    # We run on us-east-1
    # This ensure co-location with the CommonCrawl s3 bucket
    region: 'us-east-1'
    aws_access_key_id: <YOUR_KEY_ID>
    aws_secret_access_key: <YOUR_KEY>
    ec2_key_pair: key-name
    ec2_key_pair_file: /home/ubuntu/key-file.pem
    ssh_tunnel: true
    ssh_tunnel_is_open: true

    # Remember to change to a more beefier in production
    num_core_instances: 3
    instance_type: 'm1.xlarge'


    # Getting the right ami_version is important to get right.
    # https://pythonhosted.org/mrjob/guides/emr-bootstrap-cookbook.html#installing-system-packages
    image_version: '3.11.0'
    python_bin: python2.7
    interpreter: python2.7

    # These are functionally optional but realistically are not
    tags:
        project: CommonCrawl
        name: GoogleAnalytics

    bootstrap_actions:
        - s3://elasticmapreduce/bootstrap-actions/install-ganglia

    upload_files:
        - GoogleAnalytics.py

    bootstrap:
        # Get the most current versions of packaging libraries
        - sudo pip-2.7 install ujson setuptools wheel pip
        - sudo pip-2.7 install -r requirements.txt#


output-dir: "s3://bucket-name/folder-name"
```

Note:  I added the output-dir arg into the mrjob.conf to make things a bit easier to understand.
